flowchart LR

subgraph 0["src"]
subgraph 1["app"]
2["layout.tsx"]
6["manifest.ts"]
N["page.tsx"]
subgraph T["timer"]
U["page.tsx"]
end
end
subgraph 3["client"]
subgraph 4["styles"]
5["globals.css"]
end
subgraph 7["components"]
8["loading-page.tsx"]
O["home-page.tsx"]
P["timer-form.tsx"]
subgraph Q["ui"]
R["button.tsx"]
W["link.tsx"]
end
V["timer-page.tsx"]
Y["visual-timer.tsx"]
end
subgraph 9["hooks"]
A["sync.tsx"]
B["useUserId.ts"]
end
C["db.ts"]
X["nav.ts"]
end
subgraph D["lib"]
E["error.ts"]
F["time.ts"]
S["utils.ts"]
end
subgraph G["server"]
subgraph H["actions"]
I["index.ts"]
end
subgraph J["db"]
K["schema.ts"]
L["index.ts"]
end
M["env.ts"]
end
end
2-->6
2-->8
2-->A
2-->5
A-->B
A-->C
A-->E
A-->F
A-->I
F-->E
I-->K
I-->L
L-->K
L-->M
N-->O
O-->P
P-->R
P-->C
P-->F
R-->S
U-->V
U-->F
V-->C
V-->W
V-->Y
V-->E
V-->F
W-->C
W-->X
X-->C
X-->F
