flowchart LR

subgraph 0["src"]
subgraph 1["app"]
2["layout.tsx"]
6["manifest.ts"]
9["page.tsx"]
subgraph J["timer"]
K["page.tsx"]
end
end
subgraph 3["client"]
subgraph 4["styles"]
5["globals.css"]
end
subgraph 7["components"]
8["loading-page.tsx"]
A["home-page.tsx"]
B["timer-form.tsx"]
subgraph C["ui"]
D["button.tsx"]
W["link.tsx"]
end
L["timer-page.tsx"]
Y["visual-timer.tsx"]
end
G["db.ts"]
subgraph M["hooks"]
N["sync.tsx"]
O["useUserId.ts"]
end
X["nav.ts"]
end
subgraph E["lib"]
F["utils.ts"]
H["time.ts"]
I["error.ts"]
end
subgraph P["server"]
subgraph Q["actions"]
R["index.ts"]
end
subgraph S["db"]
T["schema.ts"]
U["index.ts"]
end
V["env.ts"]
end
end
2-->6
2-->8
2-->5
9-->A
A-->B
B-->D
B-->G
B-->H
D-->F
H-->I
K-->L
K-->H
L-->G
L-->N
L-->W
L-->Y
L-->I
L-->H
N-->O
N-->G
N-->R
R-->T
R-->U
U-->T
U-->V
W-->G
W-->X
X-->G
X-->H
Y-->G
Y-->N
Y-->I
