flowchart LR

subgraph 0["src"]
subgraph 1["app"]
2["layout.tsx"]
6["manifest.ts"]
9["page.tsx"]
subgraph Y["timer"]
Z["page.tsx"]
end
end
subgraph 3["client"]
subgraph 4["styles"]
5["globals.css"]
end
subgraph 7["components"]
8["loading-page.tsx"]
A["router.tsx"]
C["home-page.tsx"]
D["timer-form.tsx"]
M["timer-page.tsx"]
subgraph N["ui"]
O["link.tsx"]
10["button.tsx"]
end
P["visual-timer.tsx"]
end
E["nav.ts"]
F["routes.ts"]
G["db.ts"]
subgraph J["hooks"]
K["useUserId.ts"]
Q["sync.ts"]
end
end
subgraph H["lib"]
I["error.ts"]
L["time.ts"]
11["utils.ts"]
end
subgraph R["server"]
subgraph S["actions"]
T["index.ts"]
end
subgraph U["db"]
V["schema.ts"]
W["index.ts"]
end
X["env.ts"]
end
12["test-setup.ts"]
end
B["assert"]
2-->6
2-->8
2-->5
9-->A
A-->C
A-->M
A-->G
A-->Q
A-->K
A-->E
A-->F
A-->L
A-->B
C-->D
D-->E
D-->G
D-->K
D-->I
D-->L
E-->F
E-->G
E-->F
E-->I
M-->O
M-->P
M-->L
O-->E
O-->F
Q-->K
Q-->G
Q-->I
Q-->L
Q-->T
T-->V
T-->W
W-->V
W-->X
Z-->A
Z-->L
10-->11
12-->G
