name: Dep Lints

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: sudo apt-get install graphviz
      - run: npm ci
      - run: npm run deps:lint
      - run: npm run deps:graph
      - run: npm run deps:graph-tests
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'reports'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Axolotl-Logic CI/CD 

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: m@axolotl-logic.io

          tag_push: '--force'

